version: "3.9"

services:
  monitor:
    build: .

  storage:
    image: "redislabs/rejson:latest"
    restart: "always"
    ports:
      - "127.0.0.1:6370:6379"
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so --save 20 1 --loglevel warning
