version: "3.9"

services:
  monitor:
    build: .
    restart: "always"

  storage:
    image: "redislabs/rejson:latest"
    restart: "always"
    ports:
      - "127.0.0.1:6370:6379"
    volumes:
      - /opt/indexers/koyo/exchange/stats/:/data/
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so --save 20 1 --loglevel warning

  redis-dashboard:
    image: "rediscommander/redis-commander:latest"
    restart: "always"
    ports:
      - "127.0.0.1:6371:8081"
    environment:
      - REDIS_HOSTS=storage:storage:6379

