version: "3.9"

services:
  monitor:
    build: .
    container_name: "koyostats-monitor"
    restart: "always"
    depends_on:
      - storage
    volumes:
      - /opt/indexers/koyo/exchange/stats/exports/:/usr/src/app/json/

  storage:
    image: "redislabs/rejson:latest"
    container_name: "koyostats-storage"
    restart: "always"
    ports:
      - "127.0.0.1:6370:6379"
    volumes:
      - /opt/indexers/koyo/exchange/stats/data/:/data/
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so --save 20 1 --appendonly yes --loglevel warning

  redis-dashboard:
    image: "rediscommander/redis-commander:latest"
    container_name: "koyostats-redis-dashboard"
    restart: "always"
    depends_on:
      - storage
    ports:
      - "127.0.0.1:6371:8081"
    environment:
      - REDIS_HOSTS=storage:storage:6379

